version: '3.8'
services:
  next:
    build: ./next
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./next:/myapp
    tty: true
